[10:44] Antonio Morales Moral
-- MySQL Script generated by MySQL Workbench
-- Sat Mar 25 10:43:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; -- -----------------------------------------------------
-- Schema ayto_programa
-- ----------------------------------------------------- -- -----------------------------------------------------
-- Schema ayto_programa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ayto_programa` DEFAULT CHARACTER SET utf8 ;
USE `ayto_programa` ; -- -----------------------------------------------------
-- Table `ayto_programa`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`permisos` (
  `idpermisos` INT NOT NULL AUTO_INCREMENT,
  `nombrepermisos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpermisos`),
  UNIQUE INDEX `idpermisos_UNIQUE` (`idpermisos` ASC))
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`usuarios` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `nombreusuario` VARCHAR(45) NOT NULL,
  `correousuario` VARCHAR(45) NOT NULL,
  `telefonousurio` VARCHAR(45) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `permisos_idpermisos` INT NOT NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`idusuarios` ASC),
  UNIQUE INDEX `correousuario_UNIQUE` (`correousuario` ASC),
  UNIQUE INDEX `telefonousurio_UNIQUE` (`telefonousurio` ASC),
  INDEX `fk_usuarios_permisos1_idx` (`permisos_idpermisos` ASC),
  CONSTRAINT `fk_usuarios_permisos1`
    FOREIGN KEY (`permisos_idpermisos`)
    REFERENCES `ayto_programa`.`permisos` (`idpermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`gastos` (
  `idgastos` INT GENERATED ALWAYS AS (2022-0) VIRTUAL,
  `descripcion_gastos` VARCHAR(45) NOT NULL,
  `gasto_previsto` FLOAT NOT NULL,
  `gasto_realizado_año` FLOAT NOT NULL,
  `gasto_realizado_CF` FLOAT NOT NULL,
  `aplicacion_presupuestada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgastos`))
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`Ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`Ingresos` (
  `id_ingresos` INT GENERATED ALWAYS AS (2022-0) VIRTUAL,
  `admpublic_ingresos` VARCHAR(45) NULL,
  `gasto_previsto` FLOAT NULL,
  `ingreso_realizado_año` FLOAT NULL,
  `ingresos_realizado_importe` FLOAT NULL,
  `aplicacion_presupuestada` VARCHAR(45) NOT NULL,
  `descripcion_economica_ingresos` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ingresos`))
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`proyectos` (
  `idproyectos` INT NOT NULL,
  `descripcion_proyectos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproyectos`))
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`subvenciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subvenciones` (
  `proyectos_idproyectos` INT NOT NULL,
  `id_subvenciones` INT NOT NULL,
  `descripcion_subvenciones` VARCHAR(45) NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `fecha_planteada` DATE NULL,
  `fecha_presentada` DATE NULL,
  `fecha_provisional` DATE NULL,
  `fecha_definitiva` DATE NULL,
  `fecha_justificada` DATE NULL,
  `fecha_ingreso` DATE NULL,
  `entidad_solicitada` DATE NULL,
  `impote_publicado` INT NULL,
  `importe_solicitado` INT NULL,
  `importe_proyecto` INT NULL,
  `importe_concedido` INT NULL,
  `importe_ingresado` INT NULL,
  `importe_pagado` INT NULL,
  INDEX `fk_subvenciones_proyectos1_idx` (`proyectos_idproyectos` ASC),
  PRIMARY KEY (`id_subvenciones`),
  CONSTRAINT `fk_subvenciones_proyectos1`
    FOREIGN KEY (`proyectos_idproyectos`)
    REFERENCES `ayto_programa`.`proyectos` (`idproyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`configuracion` (
  `id` INT NOT NULL,
  `parametros` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL)
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`subvenciones_back`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`subvenciones_back` (
)
ENGINE = InnoDB; 
-- -----------------------------------------------------
-- Table `ayto_programa`.`indice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ayto_programa`.`indice` (
  `idindice` INT NOT NULL,
  `nombre_tabla` VARCHAR(45) NOT NULL,
  `tipo_valor` VARCHAR(45) NULL,
  `parametros` VARCHAR(45) NULL,
  PRIMARY KEY (`idindice`))
ENGINE = InnoDB; 
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

